name: Bug report
description: Report a bug in this project
title: "Bug: "
labels: bug
body:
  - type: textarea
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of the bug...
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      placeholder: 1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the error
    validations:
      required: true
  - type: input
    attributes:
      label: Disable YouTube Feature and Version
      placeholder: e.g., Remove YouTube Shorts 1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: User Script Manager
      placeholder: e.g., Tampermonkey, Violentmonkey, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      placeholder: Attach any relevant screenshots or screen recordings to help illustrate the issue.
